### ISSUE TITLE
Export YarpTestCase and YarpFixtureManager as a library

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-tests#1]
For building test on external repository (for example codyco software or coman/walkman software), we need to expose the Yarp stuff. 

We could create a yarp-tests library, given that this bits are iCub - indipendent, but probably requiring three different repos (`robot-testing`,`yarp-tests`,`icub-tests`) to be installed is an overkill, especially for users that don't use the superbuild. 

Another option is to simply add the cmake logic to export them as a library directly from this repo for the moment.

**Comment by apaikan** [comment]
Another possibility is to have a platform-dependent folder in the RTF. Some YARP specific plugins/macros, ... can goes into that folder which can be optionally compiled (`ENABLE_YARP`) and exported by the RTF cmake packages.  This can also solve robotology/robot-testing#15 reported by @randaz81 .

**Comment by traversaro** [comment]
@lornat75 which solution would you think would be best in the short term?

**Comment by traversaro** [comment]
I have to work on this for codyco-related testing, but we have to decide on which path to take... @lornat75 which option do you prefer ?

**Comment by lornat75** [comment]
The solution proposed by @apaikan seems good enough to me.

**Comment by traversaro** [comment]
:+1:

**Comment by traversaro** [comment]
Done in https://github.com/robotology/icub-tests/issues/4 .
