### ISSUE TITLE
different test configuration for icub CAN and icub ETH

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tests#19]
Let's separate the configuration files for testing icub CAN from icub ETH. This because icub ETH has (for now) a different tolerance when reaching a reference position and a different PWM limit. The option --context will be removed from the suits configuration files, meaning that the user will be required to explicitly set it when running the test from the command line.

**Comment by valegagge** [comment]
Done. See jointsLimits_robotCan.xml and jointsLimits_robotEth.xml
