### ISSUE TITLE
Broken installation instructions

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-tests#35]
From the installation instructions:
https://robotology.github.io/icub-tests/doxygen/doc/html/installation.html

`In case CMake fails to detect the RTF package check that you installed RTF or that you set the RTF_DIR environment variables to point to the build directory. Also check that RTF was compiled with YARP support enables (set ENABLE_MIDDLEWARE_PLUGINS and verify that ENABLE_YARP is ON).`

but ENABLE_MIDDLEWARE_PLUGINS, ENABLE_YARP does not exist in RTF...

**Comment by randaz81** [comment]
@Nicogene

**Comment by drdanz** [comment]
The instructions are outdated
* Compile RTF
* Compile YARP (enabling the `YARP_COMPILE_RTF_ADDONS` flag)
* Compile icub-tests

**Comment by Nicogene** [comment]
Hi @randaz81 ,

I have only this compilation issue in `icub-tests`:

```
/home/ngenesio/icub-tests/src/motorEncodersSignCheck/motorEncodersSignCheck.cpp: In member function ‘virtual void MotorEncodersSignCheck::run()’:
/home/ngenesio/icub-tests/src/motorEncodersSignCheck/motorEncodersSignCheck.cpp:242:33: error: ‘class yarp::dev::IPidControl’ has no member named ‘getOutput’
         RTF_TEST_FAIL_IF((ipid->getOutput((int)jointsList[i], &posout)),
                                 ^
/home/ngenesio/robot-testing/src/rtf/include/rtf/TestAssert.h:98:31: note: in definition of macro ‘RTF_TEST_FAIL_IF’
     ( RTF::Asserter::testFail(condition,\

```

but I think it is not a problem linked to `RTF`, but some tests that are outdated.

**Comment by Nicogene** [comment]
#36
