### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-tests#38]
The installation instructions written in https://robotology.github.io/icub-tests/doxygen/doc/html/installation.html are non corrected.

Moreover the note, that specifies which yarp flags need to be enabled, seems belong only to installation instructions for windows

**Comment by pattacini** [comment]
Fixed by https://github.com/robotology/icub-tests/commit/4cb50546d001941e4e8e31378a194abb4a4358bc.
