### ISSUE TITLE
Some tests don't compile

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-tests#40]
I have `yarp` `robot-testing` and `icub-main` up-to-date on `devel` branch and the following test are not compiling:

- `motor-striction` (missing `using namespace std;`)
- `opticalEncoders-drift` (missing `using namespace std;`)
- `motorEncodersSignCheck` IPidControl API changed(@randaz81)
- `jointLimits` IPidControl API changed(@randaz81)

**Comment by randaz81** [comment]
During the installation, I noticed that the instruction showns in https://robotology.github.io/icub-tests/doxygen/doc/html/installation.html, linked by https://github.com/robotology/icub-tests, are outdated.

In particular: 
`Also check that RTF was compiled with YARP support enables (set ENABLE_MIDDLEWARE_PLUGINS and verify that ENABLE_YARP is ON).`

**Comment by pattacini** [comment]
> During the installation, I noticed that the instruction shown in https://robotology.github.io/icub-tests/doxygen/doc/html/installation.html, linked by https://github.com/robotology/icub-tests, are outdated.
> 
> In particular:
> `Also check that RTF was compiled with YARP support enables (set ENABLE_MIDDLEWARE_PLUGINS and verify that ENABLE_YARP is ON).`

Fixed by https://github.com/robotology/icub-tests/commit/4cb50546d001941e4e8e31378a194abb4a4358bc.

**Comment by pattacini** [comment]
Let's take this issue as fixed on the whole because of the latest distro.
Feel free to open it up again if needed.
