### ISSUE TITLE
Unable to find RTF in devel branch

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tests#48]
I have just updated my setup which also contains `icub-tests` and I'm getting the following error

```
CMake Error at CMakeLists.txt:26 (find_package):
  By not providing "FindRTF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "RTF", but
  CMake did not find one.

  Could not find a package configuration file provided by "RTF" (requested
  version 1.3.3) with any of the following names:

    RTFConfig.cmake
    rtf-config.cmake

  Add the installation prefix of "RTF" to CMAKE_PREFIX_PATH or set "RTF_DIR"
  to a directory containing one of the above files.  If "RTF" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurrefrad!
See also "/home/gromualdi/robot-code/robotology-superbuild/build/robotology/icub-tests/CMakeFiles/CMakeOutput.log".
```

`RTF`, `YARP`, `icub-main` and `icub-test` are in `devel`. 
Actually, I think that the problem is related to the fact that `RFT` is installing a `.cmake` file called
```
RobotTestingFrameworkConfig.cmake
```
while `icub-test` is looking for `RTFConfig.cmake`
@nunoguedelha

**Comment by GiulioRomualdi** [comment]
Yes, it was exactly like this, indeed by changing 
https://github.com/robotology/icub-tests/blob/e9019bd0d0424e43c7f1fb003b482c1febf24f8a/CMakeLists.txt#L26
into 
```cmake
find_package(RobotTestingFramework 1.3.3 COMPONENTS DLL REQUIRED)
```
the error disappears. However, now I'm getting the following message
```
CMake Error at /home/gromualdi/robot-code/robotology-superbuild/build/install/lib/cmake/YARP/YARPConfig.cmake:184 (find_package):
  Could not find a package configuration file provided by "YARP_rtf" with any
  of the following names:

    YARP_rtfConfig.cmake
    yarp_rtf-config.cmake

  Add the installation prefix of "YARP_rtf" to CMAKE_PREFIX_PATH or set
  "YARP_rtf_DIR" to a directory containing one of the above files.  If
  "YARP_rtf" provides a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)
```

**Comment by traversaro** [comment]
Can you check the changes in https://github.com/robotology/icub-tests/pull/47 ? They should fix everything

**Comment by GiulioRomualdi** [comment]
Tested. It fixes the problem but then there is still a compilation error that I suppse will be addressed before merging the PR.
```
/home/gromualdi/robot-code/robotology-superbuild/robotology/icub-tests/src/positionControl-accuracy/PositionControlAccuracy.cpp:311:15: error: invalid use of incomplete type ‘class yarp::os::LogStream’
         yInfo() << "Saving file to: "<< filename;
```

**Comment by traversaro** [comment]
I think this is a consequence of https://github.com/robotology/yarp/pull/2006 . See https://github.com/robotology/visual-tactile-localization/pull/2 for an analogous fix in another repo.

**Comment by traversaro** [comment]
Actually the missing header were added on the master branch by @Nicogene  in https://github.com/robotology/icub-tests/commit/e9baf935164a244352ff7ab83fbc7863fbd4af11 . Rebasing on master should fix everything.

**Comment by pattacini** [comment]
I think we should all set here now.
Feel free to open it again if needed.
