### ISSUE TITLE
Fix Continuous Integration

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-tests#50]
It seems that Travis compilation was broken by the requirement of CMake 3.12 (see https://github.com/robotology/QA/issues/364). Instead of fixing it, perhaps it could make sense to just migrate the repo to GitHub Actions (see https://github.com/robotology/assistive-rehab/blob/master/.github/workflows/ci.yml for an example of another repo that uses GitHub Actions).

**Comment by Nicogene** [comment]
Opened a dedicated issue #52, I am working on in :+1:
