### ISSUE TITLE
missing yarpmanager.so

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-tests#8]
When running tests as suggested in the documentation:

testrunner --verbose --suit ./suits/basics-icubSim.xml

I get the following error:

[testrunner] cannot load plugin yarpmanager.so; error (load) : yarpmanager.so: cannot open shared object file: No such file or directory

**Comment by traversaro** [comment]
Perfect example of why we need automatic testing. :D I probably did something wrong while migrating the yarp fixture plugin in RTF.

**Comment by lornat75** [comment]
also, after that error the tests continue (but fail), it would be nice if the error about the fixture was fatal.

**Comment by lornat75** [comment]
the problem is that I do not have a manager related .so library in my YARP compilation... is it supposed to be a statically linked library or a plugin?

**Comment by traversaro** [comment]
Perfect example of why we need automatic testing. :D I probably did something wrong while migrating the yarp fixture plugin in RTF. Are you sure that is not the yarpmanager fixture that should be produced by RTF?

**Comment by lornat75** [comment]
It is! Maybe then the problem is the missing 'lib' prefix in the name of the library when the loader attempts to load the dynamic library of the fixture.

**Comment by traversaro** [comment]
Adding an additional `"lib"+` to https://github.com/robotology/robot-testing/blob/master/src/testrunner/src/SuitRunner.cpp#L117 is solving the issue on my machine, but I don't understand how it was working before.

**Comment by traversaro** [comment]
I guess this was fixed in https://github.com/robotology/robot-testing/commit/f7820db4d239f41a9faf26c77eec3c5840dd3395 .

**Comment by apaikan** [comment]
It seems there were two different issues: 
- testrunner returns with failure if a suit failed to run
- testurnner prevents running test suits if the fixture manager plugin cannot be found or loaded
 
The first one was already fixed as @traversaro pointed.  The second one has been  fixed in https://github.com/robotology/robot-testing/commit/fab7c5f394634d6a8ff452376a774be5ea0a1250
